name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.8, '3.8']
        pre: [false]
        include:
          - python-version: 3.8
            pre: false
          - python-version: 3.8
            pre: false
          - python-version: 3.8
            pre: false
          - python-version: 3.8
            pre: false
          - python-version: 3.8
            pre: false
          - python-version: 3.8
            pre: --pre
        exclude:
          - python-version: 3.8
            pre: --pre
          - python-version: 3.8
            pre: --pre
          - python-version: 3.8
            pre: --pre
          - python-version: 3.8
            pre: --pre
          - python-version: 3.8
            pre: --pre
          - python-version: 3.8
            pre: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -v .
        python -m pip install ${{ matrix.pre }} --upgrade pytest pytest-cov coverage
    - name: Test with coverage
      run: |
        coverage run run_tests.py
        coverage report -m
    - name: Upload coverage to Codecov
      if: matrix.python-version != '3.8'
      run: bash <(curl -s https://codecov.io/bash)
