name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.9]
        django-version: [1.9, 1.10, 1.11.17, 2.0, 2.2, 3.1, 3.2]
        exclude:
        - python-version: 3.8
          django-version: [2.0, 2.2, 3.1, 3.2]
        - python-version: 3.8
          django-version: [1.9, 1.10]
        - python-version: 3.9
          django-version: [1.9, 1.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Django ${{ matrix.django-version }}
      run: pip install Django==${{ matrix.django-version }}
    - name: Run tests
      run: python test_manage.py test

