name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel virtualenv tox coveralls

    - name: Test with tox
      run: |
        tox -e py${{ matrix.python }/./}-${{ matrix.django_version }}${{ matrix.mode }}
      env:
        DJANGO_VERSION: ${{ matrix.django_version }}
        MODE: ${{ matrix.mode }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  matrix:
    python: ["3.8", "3.8", "3.8", "3.8"]
    django_version: [dj22, dj30, dj31, dj32, djdev]
    mode: [flake8, flake8-strict, docs]
    include:
      - python: "3.8"
        env:
          MODE: flake8
      - python: "3.8"
        env:
          MODE: flake8-strict
      - python: "3.8"
        env:
          MODE: flake8-docs
      - python: "3.8"
        env:
          DJANGO_VERSION: dj30
      - python: "3.8"
        env:
          DJANGO_VERSION: dj31
      - python: "3.8"
        env:
          DJANGO_VERSION: dj32
      - python: "3.8"
        env:
          DJANGO_VERSION: djdev
