name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.9]
        django-version: ['1.11.*', '2.0.*', '2.1.*', '2.2.*', '3.0.*', '3.1.*', '3.2.*']
        exclude:
        - python-version: 3.8
          django-version: '3.0.*'
        - python-version: 3.8
          django-version: '3.1.*'
        - python-version: 3.8
          django-version: '3.2.*'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Django ${{ matrix.django-version }}
      run: pip install Django==${{ matrix.django-version }}
    - name: Install requests
      run: pip install requests
    - name: Install package
      run: pip install -e .
    - name: Test with runtests.py
      run: python runtests.py

