name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.8]
        django-version: ["<1.9", "<1.10", "<1.11", "<1.12", "<2.1", "<2.2", "<2.3", "<3.1", "<3.2"]
        mjml-version: [3.3.8, 4.3.1, 4.4.0, 4.5.1, 4.6.3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install MJML ${{ matrix.mjml-version }}
      run: |
        npm install mjml@${{ matrix.mjml-version }}
        node_modules/.bin/mjml --version
    - name: Install Django ${{ matrix.django-version }}
      run: pip install "Django${{ matrix.django-version }}"
    - name: Install requests
      run: pip install "requests>=2.20.0,<=2.24.0"
    - name: Test with python tools.py test
      run: python tools.py test

