name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8]
        django-version: ['1.11', '2.0']
        exclude:
        - python-version: '3.8'
          django-version: '2.0'
        include:
        - python-version: '3.8'
          django-version: '2.1'
        - python-version: '3.8'
          django-version: '2.2'
        - python-version: '3.8'
          django-version: '3.0'
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -U pip wheel setuptools
        pip install Django==${{ matrix.django-version }} -e .[tests]
    - name: Run tests
      run: coverage run --rcfile=.coveragerc runtests.py
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Notify on Slack
      if: ${{ failure() && github.event_name == 'push' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Github Actions
        SLACK_CHANNEL: django-fluent
        SLACK_ICON: https://avatars2.githubusercontent.com/u/13288209?s=200&v=4
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Build failed for ${{ github.repository }}
        SLACK_MESSAGE: Build failed for ${{ github.repository }} (${{ github.sha }}) with django version ${{ matrix.django-version }} and python version ${{ matrix.python-version }}
      with:
        status: ${{ job.status }}

