name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.8, 3.8, 3.8, 3.8, 3.8, 3.9, pypy-3.6]
        arch: [x64, x86]
        include:
          - os: windows-latest
            python: 3.8
            arch: x64
          - os: windows-latest
            python: 3.8
            arch: x86
          - os: windows-latest
            python: 3.8
            arch: x64
          - os: windows-latest
            python: 3.8
            arch: x86
          - os: windows-latest
            python: 3.8
            arch: x64
          - os: windows-latest
            python: 3.8
            arch: x86
          - os: windows-latest
            python: 3.8
            arch: x86
          - os: windows-latest
            python: pypy-3.6
            arch: x86
          - os: windows-latest
            python: pypy-3.6
            arch: x86

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: pip install mock
    - name: Test with unittest
      run: python -m unittest discover -p *_test.py
